import eventData from '../assets/data.json'
import Head from 'next/head'
import { EventBanner } from '../components/EventBanner'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <div className='grid grid-cols-4 gap-6 mt-6 mx-16'>
          {eventData.map(event => {
            return (
              <EventBanner
                key={event.name}
                name={event.name}
                place={event.place}
                day={event.day}
                month={event.month}
                year={event.year}
                imagePath={event.imagePath}
              />
            )
          })}
        </div>
      </main>
    </div>
  )
}
