import Head from 'next/head'
import EventForm from '../components/EventForm'

export default function Test() {
  return (
    <div>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <EventForm />

      </main>
    </div>
  )
}
